### PR TITLE
CoMD MiniApp

### PR DESCRIPTION
**Pull request by jfalkner**
Initial testing work of the CoMD MiniApp, including summary.

This does not include compiler flag optimizations and profiling work. That'll be in followup PRs.

CC @OliverPerks ready to merge!

### CODE REVIEW

**Comment by OliverPerks** [comment]
Can you add your team identification to the file too please? That way we can see who 'owns' it.

**Comment by OliverPerks** [comment]
That OpenMP scaling looks a bit off. 
Ah - Checking the CoMD Spack spec you can see `~openmp` so it has built without OpenMP support.

**Comment by jfalkner** [comment]
> Ah - Checking the CoMD Spack spec you can see ~openmp so it has built without OpenMP support.

I'll try compiling it with OpenMP. I was surprised by that too. I started reading more about the MiniApp to see if it just couldn't use it

**Comment by jfalkner** [comment]
All good. OpenMP compile done and tested. It works really well

**Pull request merged**
